// The ABSTRACTS must be put here. Each abstract is a numbered variable. Pay attention to the presence of \ at the end of each line.
 
var abstract001 = "Typical control systems designs concentrate on plant output specifications and don't always take sufficiently into account \
					specifications related to its input (e.g., coming from saturation phenomenas). This fact is especially relevant when there \
					are degrees of freedom in the plant input selection due to some kind of acuator redundancy. In this talk we will present a \
					dynamic input allocation scheme that has been proposed roughly five years ago. The core ideas behind the dynamic scheme will \
					be illustrated while discussing its recent application to: elongation and shape control for Tokamak plasmas, control of parallel \
					hybrid electric vehicles, and satellite attitude control.";
					
var abstract002 = 'Output regulation is the problem of ensuring that an output is driven to zero despite the influence of an exogenous signal \
					generated by a known system in free evolution (the "exosystem"); such a problem includes as special cases output tracking and \
					disturbance rejection for preassigned classes of references and disturbances. In classic results, when the plant is fat (i.e. it \
					has more inputs than outputs) it is just squared down a priori in order to ensure that a unique, linear regulator exists, thus \
					disregarding the infinitely many available alternatives. In this talk, starting from ideas related to input allocation and \
					focusing on linear fat plants in the presence of constraints or performance criteria, it is shown that better output regulators \
					can be obtained by scheduling inside the linear variety of linear regulators, and that optimal regulators are nonlinear even in \
					very simple cases.';

var abstract003 = 'Ultra-High Field MRI at UHF suffers from severe B1 field inhomogeneities which are detrimental to medical diagnosis. Although \
                    many powerful flip-angle homogenizing RF pulse designs have been developed to mitigate this effect, there are still numerous and \
                    useful MRI applications where the initial input for an RF pulse can be arbitrary, i.e. not necessarily longitudinal, which means \
                    that true rotation matrices need to be designed and must perform well regardless of the input magnetization state. This is a very \
                    common scenario in quantum computing applications where control schemes are designed to synthetize logic gates to be effective \
                    regardless of the input state. For that purpose, the GRadient Ascent Pulse Engineering (GRAPE) method of Khaneja et al (JMR 2005) \
                    developed within the framework of NMR quantum computing has been successfully implemented in our laboratory to design arbitrary \
                    refocusing pulses. No approximation is made so that all non-linearities and Larmor frequency offsets are fully taken into account. \
                    After introducing the theory, I will present experimental data obtained in-vitro (spin-echo) and in-vivo (SPACE, FLAIR) at 7 Tesla \
                    which demonstrates the applicability of the technique as well as the correct control of the nuclear spins.';

var abstract004 = 'We give a short introduction to the emerging field of engineering controlled quantum physical devices. For simplicity we focus on the \
                    discrete-time approach and on idealized models that are close to actual experimental realizations. We carefully introduce the basic \
                    models involved and two feedback stabilization strategies: one equivalent to classical measurement-based control, and the other \
                    working as control by interconnection. We illustrate these strategies on a quantum microwave cavity experiment from the Laboratoire \
                    Kastler Brossel at ENS Paris. <br> Related paper: \
                    Stabilization of nonclassical states of one- and two-mode radiation fields by reservoir engineering, Phys.Rev.A (2012)';
                    
var abstract005 = 'We apply two optimization methods to solve an optimal control problem of a linear neutral differential equation (NDE) arising in economics. \
                    The first one is a variational method, and the second follows a dynamic programming approach. Because of the infinite dimensionality \
                    of the NDE, the second method requires the reformulation of the latter as an ordinary differential equation in an appropriate abstract space. \
                    It is shown that the resulting Hamilton–Jacobi–Bellman equation admits a closed-form solution, allowing for a much finer characterization \
                    of the optimal dynamics compared with the alternative variational method. The latter is clearly limited by the nontrivial nature of \
                    asymptotic analysis of NDEs.  (joint with Giorgio Fabbri and Patrick Pintus)';

var abstract006 = 'We present several results of the theory of insurance demand; we experimentally test some of them and show how our experimental observations may \
                    renew the theory.';


var abstract007 = 'In this seminar a non-iterative, non-cooperative distributed state-feedback control algorithm based on neighbor-to-neighbor communication, \
                    named distributed predictive control (DPC), will be presented. Its theoretical properties, extensions, realization issues, and some \
                    of its applications will be discussed.';


var abstract008 = 'Scalability of control architectures is a central issue in networks of systems connected through physical or communication channels. \
                    In the past, several contributions addressed the problem of parallelising on-line computation of control actions using decentralized \
                    and distributed controllers. Instead, we focus on off-line design and formalize conditions that allow the synthesis of local \
                    controllers using information from neighbouring systems while guaranteeing stability and constraint satisfaction for the overall plant. \
                    This paves the way to Plug-and-Play (PnP) operations enabling the addition and removal of systems in a modular fashion by updating a \
                    limited number of local controllers within the network. Furthermore, PnP design principles can be extended to the synthesis of \
                    distributed state estimators and fault detection systems. We argue that PnP design can be very useful in the context of cyber-physical \
                    systems, where the number of subsystems changes over time, and for revamping hardware with minimal human intervention. In this talk \
                    we will present PnP design techniques for constrained systems and illustrate their application to the synthesis of the frequency \
                    control layer in power networks.';
                    
var abstract009 = 'The purpose of this talk is to present stability conditions for linear hyperbolic PDEs presenting jumps in boundary conditions and speeds. \
                    The conditions used are constructive and numerically tractable. They are based on Lyapunov theory. We will also present results \
                    control state feedback using switching controls for conservation laws. We will conclude our talk with the control of the shallow \
                    water equations by means of switching boundary controllers.';

var abstract010 = 'This talk is concerned with a class of linear hyperbolic systems of conservation laws with two time scales modeled by a perturbation parameter. \
                    By setting the perturbation parameter to zero, two subsystems, namely the reduced and boundary-layer subsystems, are computed. We first show \
                    that the stability of the full system implies the stability of both subsystems. Moreover, a counterexample is used to illustrate that the \
                    stability of the two subsystems does not guarantee the full system\'s stability. Next, the approximation between the full system and the \
                    reduced subsystem is achieved by Lyapunov technique. Finally, a boundary control synthesis to a linearized Saint-Venant-Exner system is \
                    shown based on singular perturbation method.';

var abstract011 = 'We present a brief but detailed historical review on the development of stability theory, from its early starts out of the minds of Lagrangia \
                    and Dirichlet. The survey carries on to focus on Lyapunov stability. Through exact citations from the works of the developpers of stability, \
                    including many Soviet texts from the 20th century, we revise the fundamental definitions and theorems; making emphasis on several misfortunate \
                    translations which have led to wrong interpretations and ambigous statements. We favour depth and sacrifice generality: on technical grounds, \
                    we focus on the most elementary (yet not so) well-known forms of Lyapunov stability and common but crucial qualifiers that go with it: \
                    uniform, asymptotic, global. We revise the origin of the wrongly known invariance principle ... <br><br>\
                    We hope, with this survey, to contribute \
                    to the preserving of milestones otherwise little remembered in modern texts and, hence, little known to young(er) generations.';

var abstract012 = 'One challenging and not extensively studied issue in obstacle \
                    avoidance is the corner cutting problem. Avoidance constraints are \
                    usually imposed at the sampling time without regards to the \
                    intra-sample behavior of the dynamics. This talk improves upon state \
                    of the art by describing a multi-obstacle environment via a hyperplane \
                    arrangement, provides a piecewise description of the forbidden regions \
                    and represents them into a combined mixed integer and \
                    predictive control formulation. Furthermore, over-approximation \
                    constraints which reduce to strictly binary conditions are discussed \
                    in detail.';

var abstract013 = 'This presentation describes a comprehensive framework for the cooperative guidance of a fleet of autonomous vehicles, relying on \
                    Model Predictive Control (MPC). Solutions are provided for many common problems in cooperative control, namely collision and \
                    obstacle avoidance, formation flying and area exploration. Cost functions of the MPC strategy are defined to ensure a safe \
                    collaboration between the vehicles for these applications. An efficient way to select the optimal cost with limited computation \
                    time is also provided. The performance of the proposed approach is illustrated by simulation and experimental results.';


var abstract014 = 'In this seminar, we review some recent advances in nonlinear stability theory and robust adaptive \
                    control that involve persistence of excitation theory and switching methods. Specifically, these \
                    new state-estimation and control design tools involve the construction of auxiliary filters \
                    (dynamic augmentation) ultimately leading to some strong convergence properties and \
                    robustness features. In this talk, we will specifically focus upon spacecraft attitude control \
                    systems operating under the framework of non-negligible actuator misalignments. These \
                    technical foundations are strongly motivated by growing numbers of aerospace engineering \
                    applications that are currently addressing the critical need for autonomous \
                    (and semi-autonomous) control systems with agile maneuvering and robust perception inside dynamic, complex \
                    and uncertain environments. The seminar concludes with a brief discussion of broader \
                    aerospace applications that include control over bandwidth-constrained networks and reversible \
                    transducer mechanisms for flexible spacecraft controller design.';

var abstract015 = 'This talk addresses the stability of non-autonomous linear difference equations of the form \
                    x(t) = \sum_{i=1}^N A_i(t) x(t - L_i) for positive delays L_i. When the matrices A_i are time-independent, \
                    the corresponding autonomous system can be analyzed by Laplace transform methods leading to a well-known \
                    stability criterion by Hale and Silkowski, but this technique fails to apply to the non-autonomous case. \
                    We rely rather on an explicit formula expressing the solution at time t in terms of the initial condition \
                    and time-dependent coefficients. We then relate the asymptotic behavior of such coefficients to that of \
                    solutions, which in turn leads to a necessary and sufficient stability criterion for non-autonomous \
                    difference equations. When applied to the case of switching matrices A_i(t) subject to arbitrary \
                    switching signals, one obtains a criterion in terms of a generalized joint spectral radius, which \
                    extends Hale and Silkowski\'s criterion. Corresponding stability criteria for transport and wave \
                    propagation on networks with variable coefficients are derived by expressing these systems as \
                    difference equations. In particular, we show that the wave equation on a network with arbitrarily \
                    switching damping at external vertices is exponentially stable if and only if the network is a \
                    tree and the damping is bounded away from zero at all external vertices but one. This is a \
                    joint work with Y. Chitour and M. Sigalotti.';

var abstract016 = 'In Lagrangian mechanics, constraints that can be expressed in the form of equations involving only configuration variables, \
                    and not their derivatives, are called “holonomic.” For example, a particle constrained to move on the surface of a sphere \
                    is subject to a holonomic constraint. In the case of Lagrangian control systems, one may use feedback to emulate the presence \
                    of holonomic constraints. For example, one may make a platoon of vehicles move in rigid formation by emulating the presence \
                    of distance constraints among the vehicles. Such emulated constraints are called “virtual holonomic constraints” (VHCs). \
                    In robotics, VHCs have become a popular tool to induce stable walking gaits in biped robots, and there is a growing body \
                    of work suggesting that VHCs might represent a universal paradigm for locomotion. <br><br> \
                    From a theoretical viewpoint, there are a number of interesting questions arising in the context of VHCs. \
                    One of them is whether or not the motion of a Lagrangian control system subjected to a VHC is still Lagrangian. \
                    In this second talk I will show that, in contrast with classical mechanics, the answer to this question \
                    is “typically no.” For underactuated Lagrangian control systems with underactuation degree one, \
                    I will give necessary and sufficient conditions guaranteeing that the constrained dynamics arising \
                    from a VHC are Lagrangian. I will show experimental results illustrating VHCs in action and giving \
                    an intuitive feel of the significance of Lagrangian constrained dynamics.'

var abstract017 = 'In this talk, the convergence property, which is a system-level stability property of nonlinear \
                    dynamical systems originally introduced in the 1960\'s in Russia, will be discussed in detail. \
                    A convergent system exhibits a unique, bounded globally asymptotically steady-state solution. \
                    Lyapunov characterisations of, sufficient conditions for and properties of convergent systems \
                    will be presented. Moreover, relations to notions such as e.g. incremental stability will be \
                    briefly addressed. In the second part of the talk it will be advocated that convergence is \
                    a useful property in the analysis and design of nonlinear control systems. Particular \
                    applications are: steady-state performance analysis through "nonlinear frequency response \
                    functions", output regulation (with tracking, synchronisation as particular sub-problems), \
                    observer design, model reduction and extremum seeking control.'

var abstract018 = 'Model reduction is a tool for the approximation of complex dynamical systems by systems of \
                    reduced order, hereby enabling efficient analysis or controller synthesis. In this presentation, \
                    several methods for model reduction of nonlinear systems will be discussed. These methods \
                    have in common that they rely on incremental system properties in obtaining an accurate \
                    reduced-order model that preserves relevant stability properties and satisfies an a priori \
                    bound on the reduction error. Specifically, (input-to-state) convergent nonlinear systems \
                    will be considered, in which reduction is performed by isolating the nonlinearities and the \
                    application of linear model reduction techniques. Next, the reduction technique of \
                    incremental balanced truncation is introduced, which explicitly takes nonlinearities into \
                    account in the reduction procedure and can be regarded as an extension of the well-known \
                    technique of balanced truncation to the nonlinear domain.'

var abstract019 = 'Contact stability in humans and robots is guaranteed by generating task-adapted restoring \
                    forces in response to the environmental displacements, which can be achieved using different \
                    techniques. For instance, in humans, muscle activations can modify the joint stiffness matrix \
                    via cocontraction of muscles involved in the task, or through modifications in the sensitivity \
                    of reflex feedback. Similarly in robots, the joint stiffness profile can be adjusted to realize \
                    a desired compliant behavior in Cartesian coordinates through conservative congruence transformations.<br><br>\
                    Endpoint stiffness in different directions, often represented by stiffness ellipsoids, is also \
                    modified by varying the geometry of the arm; due to this geometric dependence, endpoint stiffness \
                    is subject to variations depending on the position of the endpoint in task space, or even on \
                    the arm configuration for the same end-effector position, when the arm is redundant. Observations \
                    in human neuromotor control of the arm endpoint stiffness suggest that due to i) the major \
                    contribution of the limb geometry to efficient modifications in the orientation of the endpoint \
                    stiffness ellipsoid, ii) ergonomic efficiency of postural adjustments in comparison to cocontractions, \
                    and iii) the existence of cross-joint muscles in limbs, humans tend to maximize the use of limb \
                    postures to realize a desired endpoint stiffness direction. Concurringly, cocontractions appear \
                    to mostly contribute to modifications in size, rather than orientation of the stiffness ellipsoid.<br><br> \
                    Relying on the above observations, in this talk, a reduced complexity model of the human arm endpoint \
                    stiffness is introduced for real-time and cost-efficient tracking of the human\'s physical interaction \
                    behavior. Next, the underlying motor control principles, namely common-mode and configuration-dependent \
                    stiffness, are exploited for the design of the compliant robots\' control architecture with the aim \
                    to achieve a human like physical interaction behavior.'

var abstract020 = 'Since its relatively recent birth, control systems theory has reached \
                    outstanding results in the understanding of feedback systems and in \
                    the design of effective solutions for an enormous variety of \
                    applications, substantially contributing to the improvement of the \
                    quality of life of citizens.  What are the new challenges to progress \
                    further? Many agree that a crucial one is the ability to cope with \
                    complexity, as it arises e.g. in the domains of life and social \
                    sciences. In the endeavour of understanding, regulating, and even \
                    replicating natural systems and social organizations, an enormous \
                    potential resides in the combination of powerful analytical tools and \
                    ideas and inspirations that comes from studies in the neurosciences.<br><br> \
                    In this talk I will present some examples of how this process can \
                    work, reporting on few case-studies, mainly from Robotics, where a fruitful \
                    multidisciplinary collaboration has led to interesting insight and \
                    technological solutions. The talk will however focus mostly on open \
                    questions and discussion points.'

var abstract021 = 'Reaction networks are systems in which the populations of a finite number of species evolve according \
                    to predefined interactions. Such networks are found as modeling tools in many disciplines (spanning \
                    biochemistry, epidemiology, pharmacology, ecology and social networks). Traditionally, reaction \
                    networks are mathematically analyzed by expressing the dynamics as a set of ordinary diﬀerential \
                    equations. Such a deterministic model is reasonably accurate when the number of network participants \
                    is large. However, when this is not the case, the discrete nature of the interactions becomes \
                    important and the dynamics is inherently noisy. This random component of the dynamics cannot be \
                    ignored as it can have a signiﬁcant impact on the macroscopic properties of the system. This is \
                    the reason why stochastic models for reaction networks are necessary for representing certain \
                    reaction networks. The tools for analyzing them, however, still lag far behind their deterministic \
                    counterparts.<br><br> The objective of this talk is to introduce the stochastic modeling paradigm for \
                    reaction networks with an emphasis towards biology. It will be shown that the trajectories of such \
                    processes can be represented by a jump Markov process over the nonnegative integer lattice. Two \
                    problems will then be addressed. The first one is related to the stability of these processes while \
                    the second one is related to their control. Regarding stability, it will be shown that the ergodicity \
                    of the such processes can be, in many cases, efficiently established using linear programs, well \
                    known for their tractability. These conditions will then be applied on several reaction networks \
                    arising in fields such as biochemistry, epidemiology and ecology. Finally, the problem of \
                    controlling single-cell dynamics or cell populations using in-vivo controllers will be addressed. \
                    Several theoretical  properties for the closed-loop system (robustness, non-fragility, tracking, \
                    disturbance rejection, etc) will be emphasized and illustrated through several examples.'


var abstract022 = 'Temporal dynamic control of gene expression can have far reaching implications for bioprocess \
                    regulation and optimization, among other biotechnology applications. Thanks to the advantages \
                    of light as a modulator, optogenetics has emerged as an ideal technology for achieving such \
                    gene expression control. Current state-of-the-art methods for optical expression control fail \
                    to combine precision and repeatability, and cannot withstand changing operating conditions in \
                    cell cultures. We present a novel fully automatic experimental platform for the robust and \
                    precise long-term optogenetic regulation of protein production in liquid E. coli cultures. \
                    Using a computer-controlled light-responsive two-component system, we accurately track \
                    prescribed dynamic GFP expression profiles through the application of feedback control. \
                    The achieved tracking precision is shown to robustly adapt to global perturbations such as \
                    abrupt switching of media and large temperature changes. We finally provide the implementation \
                    details and compare the performance of the two alternative control strategies used: a \
                    simple PI scheme and a more elaborate MPC controller coupled to a particle filter for \
                    online state, parameter and disturbance estimation.'

var abstract023 = 'We consider linear infinite dimensional control systems with unbounded and periodic evolution, \
                    input and output operators, and mixed discrete/continuous time in state and measurement equations. \
                    In the first section we introduce the concepts of left and right admissible input and output operators, \
                    and generalized Pritchard-Salamon system. In the second section we study perturbation results. \
                    The third section is devoted to dual operators and dual Pritchard-Salamon systems. In the next \
                    section we introduce and study the concepts of admissible stabilizability and detectability, \
                    and get stability criteria. Dynamic output feedback is the subject of section five. Next, we \
                    formulate the standard H-infinity control problem with arbitrary cost quadratic functional. \
                    It is solved first for the case of systems with full measurements, and then in the general case. \
                    A discussion of all results concludes the presentation.'

var abstract024 = 'For linear systems in continuous time with random switching, the Lyapunov exponents are characterized \
                    using the Multiplicative Ergodic Theorem for an associated system in discrete time. An application to \
                    control systems shows that here a controllability condition implies that arbitrary exponential decay \
                    rates for almost sure stabilization can be obtained. This talk is based on joint work with Guilherme Mazanti.'

var abstract025 = 'Let us consider two vector fields, each one of which possesses a unique stable equilibrium, and a \
                    stochastic process following alternatively the two associated flows with random switching times. \
                    We are interested in the long time behavior of this process. More precisely, we investigate how \
                    its stability depends on the alea of the switchings. Finally, we relate this problem to some \
                    questions in a deterministic control setting.'
                    
var abstract026 = 'Milton Erikson used to tell a story, that a centipede was asked how it was able to move all \
                    the hundred legs in such a synchronous way. After this question had been put to the poor \
                    creature, it had been unable to make a step ever since.<br><br>The centipede tale is not \
                    so meaningless as it seems from a first glance. There is an evidence that wave-like motions \
                    of centipede\'s legs are generated by a spatially distributed neural network rather than by \
                    a local generator.<br><br>Apparently a very primitive and distributed nervous system can \
                    generate complex wave-like patterns and this problem will be addressed in the talk.<br><br> \
                    In particular it will be shown how the symmetries of the network can contribute to the \
                    existence of linear invariant manifolds which could be associated with in-phase and \
                    anti-phase behavior of the networks\' nodes. Those linear manifolds can be represented \
                    as kernels of some linear operators and the distance to those sets can play a role of \
                    Lyapunov functions which prove stability of those regimes.<br><br>The talk is illustrated \
                    by some examples.'

var abstract027 = 'The ISS theory and its characterizations by means of Lyapunov dissipation inequalities are presented \
                    for the systems admitting invariant sets, which are not necessarily stable in the sense of Lyapunov, \
                    but admit a suitable hierarchical decomposition. The proposed theory is applied to oscillators in \
                    Euclidean coordinates, almost globally asymptotically stable systems on manifolds, systems with \
                    multiple equilibria, limit cycles, etc.'

var abstract028 = 'In this talk we propose a Lyapunov based analysis of microgrids. The starting point is an energy \
                    function comprising the kinetic energy associated with the elements that emulate the rotating \
                    machinery and terms taking into account the reactive power stored in the lines and dissipated \
                    on shunt elements. We then shape this energy function with the addition of an adjustable \
                    voltage-dependent term, and construct incremental storage functions satisfying suitable \
                    dissipation inequalities. The choice of the voltage-dependent term depends on the voltage \
                    dynamics/controller under investigation. Several microgrids dynamics that have similarities \
                    or coincide with dynamics already considered in the literature are captured in this incremental \
                    energy analysis framework. These incremental storage functions allow for a complete analysis \
                    of the coupled microgrid obviating the need for simplifying linearization techniques and for \
                    the restrictive decoupling assumption in which the frequency dynamics is fully separated \
                    from the voltage one.'

var abstract029 = 'A major transition in the operation of electric power grids is the replacement of bulk \
                    generation based on synchronous machines by distributed generation based on low-inertia \
                    power electronic sources. The accompanying "loss of rotational inertia" and the fluctuations \
                    by renewable sources jeopardize the system stability, as testified by the ever-growing \
                    number of frequency incidents. As a remedy, numerous studies demonstrate how virtual \
                    inertia can be emulated through various devices, but few of them address the question of \
                    "where" to place this inertia. It is however strongly believed that the placement of \
                    virtual inertia hugely impacts system efficiency, as demonstrated by recent case studies. \
                    We carry out a comprehensive analysis in an attempt to address the optimal inertia placement \
                    problem, considering a linear network-reduced power system model along with an H2 performance \
                    metric accounting for the network coherency. The optimal inertia placement problem turns \
                    out to be non-convex, yet we provide a set of closed-form global optimality results for \
                    particular problem instances as well as a computational approach resulting in locally \
                    optimal solutions. We illustrate our results with a three-region power grid case study \
                    and compare our locally optimal solution with different placement heuristics in terms \
                    of different performance metrics.'

var abstract030 = 'An inverse control problem is formulated as follows: given a set of trajectories and \
                    a control system, find a cost such that these paths are optimal. The first question \
                    to ask is the uniqueness of the solution of such a problem. For general classes of costs \
                    the problem appears to be very difficult, even with a trivial dynamics. We are therefore \
                    interested in this issue for the class of costs which are quadratic in the control, \
                    when the dynamics depend linearly in the control (Riemannian and sub-Riemannian case). \
                    In this case we can reduce the problem to the question of the existence of geodesically \
                    equivalent metrics and the existing results will be described, from the theorem of Levi-Civita \
                    (1890) to those we obtained recently with Sofya Maslovskaya and Igor Zelenko.'

var abstract031 = 'The use of Lyapunov functions is generally limited to proving the stability of a system \
                    with a given control law. In this presentation, Lyapunov functions are used to formulate \
                    optimal control problems as pointwise nonlinear programmes. These optimisation problems \
                    are equivalent to inverse optimal control problems. This approach is applied to satellite \
                    attitude control. The optimal attitude control problems under consideration will be the \
                    minimisation of the norm of the control torque subject to constraints on the convergence \
                    rate of a Lyapunov function. This approach improves the tradeoff between rapidity and \
                    energy consumption compared to a benchmark controller, which is taken to be a PD type \
                    controller without loss of generality. The phase space trajectories show that the solutions \
                    to some fundamental open loop optimization problems are particular cases of optimal control \
                    problem formulations based on the convergence rates of Lyapunov functions. This is the \
                    case of the minimum time single axis attitude control problem, which is a special case \
                    of the  problem of maximizing the convergence rate of a Lyapunov function under maximum \
                    torque limitations. It is also the case of the problem of minimising toque for fixed \
                    manoeuvre time. The solution to this problem is a particular case of the problem of \
                    minimizing the norm of the control torque under a Lyapunov convergence rate constraint.'

var abstract032 = 'This talk deals with the stabilization in the sample-and-hold sense of nonlinear systems \
                    described by retarded functional differential equations. The notion of stabilization in \
                    the sample-and-hold sense has been introduced in 1997 by Clarke, Ledyaev, Sontag and Subbotin, \
                    for nonlinear delay-free systems. Roughly speaking, a state feedback (continuous or not) \
                    is said to be a stabilizer in the sample-and- hold sense if, for any given large ball and \
                    small ball of the origin, there exists a suitable small sampling period such that the \
                    feedback control law obtained by sampling and holding the above state feedback, with \
                    the given sampling period, keeps uniformly bounded all the trajectories starting in any \
                    point of the large ball and, moreover, drives all such trajectories into the small ball, \
                    uniformly in a maximum finite time, keeping them in, thereafter. In this talk suitable \
                    control Lyapunov-Krasovski functionals will be introduced and suitable induced state \
                    feedbacks (continuous or not), and it will be shown that these state feedbacks are \
                    stabilizers in the sample-and- hold sense, for fully nonlinear time-delay systems. \
                    Moreover, in the case of time-delay systems, implementation by means of digital \
                    devices often requires some further approximation due to non availability in the \
                    buffer of the value of the system variables at some past times, as it can be frequently \
                    required by the proposed state feedback. In order to cope with this problem, well known \
                    approximation schemes based on first order splines are used. It is shown, for fully \
                    nonlinear retarded systems, that, by sampling at suitable high frequency the system \
                    (finite dimensional) variable, stabilization in the sample-and-hold sense is still \
                    guaranteed, when the holden input is obtained as a feedback of the (first order) \
                    spline approximation of the (infinite dimensional) system state, whose entries are \
                    available at sampling times, and the state feedback is Lipschitz on any bounded \
                    subset of the Banach state space.'

var abstract033 = 'In a feedback system, besides the stabilization, the controllers are often designed to \
                    meet some performance specifications defined by <font face="Cursive">H</font>&infin; \
                    norm minimization of corresponding sensitivity functions. From the practical point of view, \
                    if it is possible, it is desired the controller to be designed is stable. In this work, stable \
                    controller design to minimize the <font face="Cursive">H</font><sub>&infin;</sub> norm of \
                    the corresponding sensitivity function in a feedback system with a single-input single-output \
                    biproper infinite-dimensional real plant is considered. \
                    The plant may have infinitely many poles and simple zeros in the right-half-plane, however, it is \
                    zeros are assumed to satisfy some growth condition. Interpolation-based approach will be used to \
                    design such a controller and a numerical example will be presented.'

var abstract101 = 'To extend spacecraft operational life, control techniques that can accommodate actuator failures, reduce the use of fuel and avoid collisions with debris are of interest. Such techniques may need to exploit "higher order" physical effects, such as forces and torques normally considered as disturbances, approaches that can take advantage of nonlinearities in spacecraft kinematics and dynamics, and handle stationary and moving obstacle avoidance requirements. Hence spacecraft operational life extension problems create many potential opportunities for the application of nonlinear, optimal and constrained/predictive control.</br>\
After general remarks on control challenges and opportunities in spacecraft operational life extension problems, the presentation will focus on related recent case studies. </br>\
In particular, it will be shown that for a spacecraft with only two functioning reaction wheels linear controllability of attitude dynamics can be regained, under appropriate assumptions, if solar radiation pressure torques are included in the analysis. This conclusion can be exploited for handling reaction wheel failures based on conventional linear controllers.  Alternative approaches that do not rely on the solar radiation pressure torques but exploit nonlinearities in the spacecraft kinematics and dynamics will also be discussed. Furthermore, an intriguing capability of model predictive controllers to achieve discontinuous stabilization in underactuated spacecraft attitude control problems will be highlighted. We will also touch upon coupled translational and rotational relative motion dynamics of a rigid spacecraft in central gravity field and potential opportunities to move translationally in space by employing attitude control only.  In the final part of the presentation, drift counteraction optimal control problems for systems with drift and/or large disturbances will be introduced, in which the objective is to maximize the time for a system to violate prescribed constraints. Potential applications of drift counteraction optimal control, including for geostationary satellite orbit maintenance and drag induced orbit decay compensation, will be discussed'

var abstract102 = 'An innovative framework for the control of stochastic process by means of an optimization problem on the Fokker-Planck equation is presented. The time dependent probability density function (PDF)  as representative of the dynamical state of a stochastic system is used, hence the governing Kolmogorov-Fokker-Planck-type (KFP) equation is employed as a constraint for the minimization of a cost function. The problem to find a controller that minimizes the cost function can be solved by solving an optimality system of time dependent forward and backward partial differential equations. A short review of control objectives, KFP equations and numerical techniques to tackle the optimization problem, is shown by using models from biology, physics, and finance.'

var abstract103 = 'We investigate a moral hazard problem in finite time with lump-sum and continuous payments, involving infinitely many Agents, with mean field type interactions, hired by one Principal. By reinterpreting the mean-field game faced by each Agent in terms of a mean field FBSDE, we are able to rewrite the Principal\'s problem as a control problem for McKean-Vlasov SDEs. We solve completely and explicitly the problem in special cases, going beyond the usual linear-quadratic framework.'

var abstract104 = 'TBA'


// ----------------------------------------------------- FUNCTIONS -----------------------------------------------------
			function insertAbstractToggle(absnumstr) {
				var absstr = 'abstract' + absnumstr;
				var txt = "<div id=\"hide_part" + absnumstr + "\" style=\"display:none;\"> \n"
						+ "<p class=\"sem_abstract\" style=\"text-align: justify;text-justify: inter-word;\"><strong>Abstract</strong><br> \n"
						+ eval(absstr) + " \n"
						+ "</p> \n"
						+ "<a href=\"javascript:;\" onClick=\"document.getElementById('show_part" + absnumstr + "').style.display='block';"
						+ "document.getElementById('hide_part" + absnumstr + "').style.display='none';\">&#8657; </a> \n"
						+ "</div> \n"
						+ "<div id=\"show_part" + absnumstr + "\" style=\"display:block;\"> \n"
						+ "<a href=\"javascript:;\" onClick=\"document.getElementById('show_part" + absnumstr + "').style.display='none';"
						+ " document.getElementById('hide_part" + absnumstr + "').style.display='block';\">Abstract &#8659;</a> \n"
						+ "</div> \n";
					
				return txt;
			}
